---
- name: Update all installed packages using APT module
  hosts: all
  tasks:
     - name: start apt
       ansible.builtin.apt:
          name: '*'
          state: latest
          update_cache: yes
          only_upgrade: yes
       register: apt_update_status
